name: pipeline
on:
  push:
    branches:
      - "main"

permissions:
  packages: write

jobs:
  deploy-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: prod
          push: true
          tags: |
            ghcr.io/maxisusi/max-blog:latest
            ghcr.io/maxisusi/max-blog:${{ github.sha }}
